### ISSUE TITLE
Using `@name` stops rendering the output

### ISSUE THREAD

**Issue by ghost** [SassDoc/sassdocmeister#1]

**Comment by valeriangalliat** [comment]
Thanks for reporting the bug.

There was a problem in console color support detection in SassDoc, not working in the browser. Fixed it in SassDoc 2.1.7, and updated SassDocMeister; `@name` is now working!

Refs: https://github.com/SassDoc/sassdoc/commit/dc081720f2a562d24caadabc2a4ae8d70025254f
