### ISSUE TITLE
General functionality issues

### ISSUE THREAD

**Issue by ghost** [SassDoc/sassdocmeister#2]
Getting several console errors on any input: either `Cannot read property 'emit' of undefined` when adding to the default template or `Cannot read property 'privatePrefix' of undefined` when pasting in a template. Chrome 41.0.2272.118 (64-bit) on Mac with no extensions installed.

**Comment by valeriangalliat** [comment]
Hey, sorry for the delay. I just updated dependencies and recompiled the script, and it works again!
