### ISSUE TITLE
Something breaks when editing

### ISSUE THREAD

**Issue by giuseppeg** [SassDoc/sassdocmeister#3]
When editing / pasting a block of code with docs I get the following error.

<blockquote>Uncaught TypeError: Cannot read property 'privatePrefix' of undefined</blockquote>

Seems like that `env` is `undefined`, maybe some bug with the transpiler or the build.

The tool is not working at this point.

<img src="https://photos-3.dropbox.com/t/2/AAACLT1x7TDZstBbUrQL6KHqu9OvD7NSW-75ZohRURKtHw/12/3113573/png/32x32/1/1436522400/0/2/Screenshot%202015-07-10%2010.37.09.png/COWEvgEgASACIAMgBCAFIAYgBygBKAI/OuWhv1qDmQp-K8JRIDeOlwoqjJX4qHtBFEW54PZEPqQ?size=1024x768&size_mode=2" alt>

**Comment by valeriangalliat** [comment]
Should be okay, please reopen if you still have a bug!

**Comment by giuseppeg** [comment]
Yeah it works now @valeriangalliat++
